okta:
  oauth2:
    issuer: https://dev-rec3ln078k3h6rbf.us.auth0.com/
    client-id: gGrdylqhWCLDgrvcsA6QpJDK4DcO7fJc
    client-secret: oOsNX2UZsOLa75vKdrEydvmwAVAz3LTawBHVySK4eRZzb6_G9fj3w8isZhUvNx24
