okta:
  oauth2:
    issuer: https://dev-gwz5xsegioo0i4cw.uk.auth0.com/
    client-id: y3Kctt8SBfC4xYcblod2uKESDJHbCMo8
    client-secret: egHWo_EiD9Jf8N9QQHcgL6YA5rVgOzoDZxeE2vEPxCRZuemPsGkGbXA7syyw0Qw9
