okta:
  oauth2:
    issuer: https:/dev-vt0na45svhpo7sfe.uk.auth0.com/
    client-id: 7lTIozbqC0HLDR44Dzpquo6z4gOiZVsI
    client-secret: VYpAlohHPYj0IosXSfmsuHvLra-roIdhuAp0ip5Q4tLZbmkoL2TqYymI1MwoRo6j